# Generated by Django 2.2.11 on 2021-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationinfo',
            name='discounted_prices',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠价格'),
        ),
        migrations.AlterField(
            model_name='specificationinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
    ]
