# Generated by Django 2.2.11 on 2020-11-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfoimage',
            options={'verbose_name': '产品详细图片', 'verbose_name_plural': '产品详细图片'},
        ),
        migrations.AlterField(
            model_name='productinfoimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_image', to='ProductManagement.ProductInfo', verbose_name='对应商品'),
        ),
        migrations.AlterField(
            model_name='specificationinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='ProductManagement.ProductInfo', verbose_name='对应商品'),
        ),
    ]
