# Generated by Django 2.2.11 on 2020-11-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0002_auto_20201116_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfoimage',
            old_name='iamge',
            new_name='image',
        ),
    ]
