# Generated by Django 2.2.17 on 2020-11-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单',
                'ordering': ('id',),
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderFormStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='状态名称')),
            ],
            options={
                'verbose_name': '订单状态',
                'ordering': ('name',),
                'verbose_name_plural': '订单状态',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '产品总分类',
                'ordering': ('id',),
                'verbose_name_plural': '产品总分类',
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_quantity', models.IntegerField(default=0, verbose_name='购买数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='BusinessManagement.OrderForm', verbose_name='关联的订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManagement.SpecificationInfo', verbose_name='商品')),
                ('shopping_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='BusinessManagement.ShoppingCart', verbose_name='关联的购物车')),
            ],
            options={
                'verbose_name': '商品清单',
                'ordering': ('id',),
                'verbose_name_plural': '商品清单',
            },
        ),
        migrations.AddField(
            model_name='orderform',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessManagement.OrderFormStatus'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
