# Generated by Django 2.2.11 on 2020-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('id',), 'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.AddField(
            model_name='orderform',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='订单总价'),
        ),
    ]
