# Generated by Django 2.2.11 on 2021-01-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessManagement', '0002_auto_20201215_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderformstatus',
            name='code',
            field=models.CharField(default=1, max_length=200, verbose_name='状态代码'),
            preserve_default=False,
        ),
    ]
