# Generated by Django 2.2.11 on 2021-01-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessManagement', '0003_orderformstatus_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='product',
            new_name='specification',
        ),
    ]
