# Generated by Django 2.2.11 on 2021-02-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessManagement', '0004_auto_20210119_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='order_code',
            field=models.CharField(default=1, editable=False, max_length=200, unique=True, verbose_name='订单号'),
            preserve_default=False,
        ),
    ]
